name: CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

# required for upload
permissions:
  contents: write

jobs:

  Linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-24.04, ubuntu-24.04-arm ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt update -y && make ubuntu-install-deps

      - name: Build zip
        run: make linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.zip

  MacOS:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ macos-latest, macos-13 ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install
        run: make macos-install-deps

      - name: Build zip
        run: |
           make mac

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.zip            
